"""
dashboard/components/live_feed.py

Live CCTV feed component for the AI-Assisted Exam Proctoring Dashboard.
"""

from __future__ import annotations

from pathlib import Path

import streamlit as st


DEFAULT_FRAME_PATH = Path("dashboard/assets/latest_frame.jpg")


def render_live_feed(frame_path: Path | str = DEFAULT_FRAME_PATH) -> None:
    """
    Render the latest annotated CCTV frame.

    Parameters
    ----------
    frame_path:
        Path to the latest annotated frame generated by app.py.
    """

    st.subheader("📹 Live CCTV Feed")

    frame_path = Path(frame_path)

    frame_placeholder = st.empty()

    if frame_path.exists():
        frame_placeholder.image(
            str(frame_path),
            caption="Live Annotated CCTV Feed",
            use_container_width=True,
        )
    else:
        frame_placeholder.info(
            "Waiting for live camera feed..."
        )